# Generated by Django 3.0.8 on 2020-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_return_due', models.DateField()),
                ('second_return_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveServicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('income_tax_activate', models.BooleanField()),
                ('gst_tax_activate', models.BooleanField()),
                ('companies_activate', models.BooleanField()),
                ('accounting_activate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesActModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_return_due', models.DateField()),
                ('second_return_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('first_due_1', models.DateField()),
                ('first_due_3b', models.DateField()),
                ('annual_return', models.DateField()),
                ('audit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_install_due', models.DateField()),
                ('second_install_due', models.DateField()),
                ('third_install_due', models.DateField()),
                ('fourth_install_due', models.DateField()),
                ('tax_return_date', models.DateField()),
                ('tds_return_date', models.DateField()),
                ('audit_date', models.DateField()),
            ],
        ),
    ]
